name: CD-React

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build-frontend:
    name: Build frontend bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build static bundle
        run: pnpm --filter frontend build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-bundle
          path: ./frontend/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-frontend]
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.2

      - name: Load frontend static bundle
        uses: actions/download-artifact@v3
        with:
          name: frontend-bundle
          path: ./frontend/dist

      - name: Create Terraform variable file
        working-directory: ./aws/
        run: echo "$TFVARS" > terraform.tfvars
        env:
          TFVARS: ${{ secrets.TF_VARS }}

      - name: Terraform Init
        working-directory: ./aws/
        run: terraform init

      - name: Terraform Plan
        working-directory: ./aws/
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./aws/
        run: terraform apply -auto-approve -input=false
