name: CI-Deploy

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'aws/**'
      - 'docker/**'

  push:
    branches:
      - main
    paths:
      - 'aws/**'
      - 'docker/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

jobs:
  validation:
    name: validate terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        working-directory: ./aws
        run: terraform init

      - name: Terraform Validation
        working-directory: ./aws
        run: terraform validate

  docker-build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          push: false
          tags: human-trust/kafa-staging:latest
